### PR TITLE
Included a native method for IEEEremainder

### PR DESCRIPTION
**Pull request by AnishChandran**

### CODE REVIEW

**Comment by perimosocordiae** [comment]
As far as I know there isn't a Javascript function for IEEEremainder, so I'm not sure how this could work.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math

**Comment by AnishChandran** [comment]
Oh ! sorry ! I just had a look at http://www.tutorialspoint.com/java/lang/math_ieeeremainder.htm and thought that there is IEEEremainder function ! But the tests ran well ! I will restore it back

**Comment by AnishChandran** [comment]
Can you suggest me with some native functions to work with ?!

Anish

**Comment by perimosocordiae** [comment]
Any of the StrictMath functions that we haven't implemented yet are good choices, though they're not always very interesting. Really, any native (in these files https://github.com/plasma-umass/doppio/tree/new-objects/src/natives) that currently throws an `UnsatisfiedLinkError` is a good candidate.

**Comment by AnishChandran** [comment]
hey I just wanted to ask one more thing ! y there are no tests for the trignometric functions in the StrictMathTest.java ?
https://github.com/plasma-umass/doppio/blob/master/classes/test/StrictMathTest.java#L299

**Comment by perimosocordiae** [comment]
Because we never got around to writing them, it seems! We would definitely appreciate more test coverage.

**Pull request closed without merging**
