### PR TITLE
configurable responsiveness

### LINKED ISSUE #404: Can the `responsiveness` setting be exposed through options?
The `JVMThread.run()` method uses a `responsiveness` variable to break out of its while loop. If I understand right, this is a form of co-operative scheduling, where the thread yields to other threads (browser native event-loop or other JVM threads).

The `responsiveness` is hard-coded to `1000 ms`. Is this something that can be exposed via doppio options?

### PR DESCRIPTION
**Pull request by hrj**
responsiveness can now be specified in doppio options, either as:
* a number
* a function that returns a number

The number is interpreted as a duration in milliseconds after which the thread should yield.

Closes #404

### CODE REVIEW

**Comment by hrj** [comment]
If #408 gets merged, I will refresh this PR so that the tests run again.

**Comment by jvilk** [comment]
Looks good to me. Once you refresh the PR, I'll merge this in.

**Comment by hrj** [comment]
PR updated and checks passed!

**Comment by jvilk** [comment]
Thanks again!

**Pull request merged**
