### PR TITLE
WIP: New objects rewrite

### PR DESCRIPTION
**Pull request by perimosocordiae**
I'm opening this as a pull request to get the ball rolling. One day, doppio's house will be united again!

Pre-merge checklist:
 - [ ] fix merge conflicts
 - [ ] test the demo
 - [x] Make sure large demo projects still work
  * Most notably, Nashorn doesn't work. @jvilk is working on it.
 - [x] Check speed relative to demo / master
  * It's *much* slower atm on JAR files because it's using Jazzlib to decompress files, and I think it's suspending the event loop more for class resolutions that could be done synchronously. I want to know what the raw numbers are and be reasonably sure about slowdown sources so I can make them into issues before hitting the merge button.
 - [ ] Documentation
   * People want to use DoppioJVM, and it's (understandably) hard to do so.

### CODE REVIEW

**Comment by Nintendud** [comment]
- [ ] Make sure large demo programs still work
  - Most notably, Nashorn isn't working. I'm working on it now.

**Comment by jvilk** [comment]
- [ ] Make sure large demo projects still work
  * Most notably, Nashorn doesn't work. I'm working on it.

**Comment by jvilk** [comment]
Speed report: `new-objects` is *slightly* slower than `master`. And both are 2X slower than our current demo.

Why is this the case?

* **We switched to using `AppClassLoader` for loading items on the user-provided classpath.**
  * Now, JAR files are decompressed in 100% Java because we use Jazzlib instead of implementing the JVM natives for Zip files.
  * Note that we can hook up BFS's zip file support directly up to these natives.
* **We/I have not profiled `new-objects` for low-hanging fruit.**
  * There are likely a number of places where a fast path will make a noticeable performance difference.

In any case, since both `master` and `new-objects` are similarly slow, this is not an obstacle to merging.

Next up: Ensuring `new-objects` works with `doppio-demo`! I've created a `doppio-demo` branch to test this out, which requires a `doppio_jcl` update to automatically produce a 100% JAR-file JCL. Currently, `doppio-demo` is using a manually produced 100% JAR file JCL that is incompatible with `new-objects` due to native method changes.

Todo before merge:

- [ ] Automate producing 100% JAR file JCL.
- [ ] Update `doppio-demo`'s `new-objects` branch to use this JCL.
- [ ] Test `new-objects` with `doppio-demo`.

Todo after merge:

- [ ] Update documentation to reflect internal API changes for natives.

**Comment by jvilk** [comment]
It is done. Finally. I didn't get to the JDK changes mentioned above, but there's no point in keeping development bifurcated any longer.

**Comment by perimosocordiae** [comment]
Woo finally! Nice work, John. :shipit:

**Pull request merged**
