### PR TITLE
Support Java 8

### PR DESCRIPTION
**Pull request by perimosocordiae**
This is the tracking PR for issue #299.  **Do not merge until the tasks are completed!**

- [x] Clean up the grunt configuration stuff
- [x] Add missing natives
- [x] Remove old Java 6 natives that we no longer need
- [x] Make sure all current unit tests pass
- [x] Add unit tests that cover polymorphic functions
- [x] Add unit tests that cover InvokeDynamic and other new features
- [x] Add unit tests that cover new [default interface methods](http://zeroturnaround.com/rebellabs/java-8-explained-default-methods/).
- [x] Add unit tests that cover the extended invokeVirtual semantics
- [x] Add support for new constant pool items to `ldc` (e.g. `MethodHandle`, `MethodType`...).
- [x] Make sure all big programs still work:
  - [x] javac
 -  [x] javap
 -  [x] rhino
 -  [x] kawa

### CODE REVIEW

**Comment by jvilk** [comment]
All I need to do is fix the browser build, which I'll do tomorrow, and I will merge this in.

Then, it's on to even bigger and better changes!

**Comment by jvilk** [comment]
StreamTest fails to terminate in the browser, so I need to take a look at that next...

**Comment by jvilk** [comment]
And by 'fails to terminate', I mean that no JavaScript is running, so a thread didn't terminate in the expected manner.

**Comment by perimosocordiae** [comment]
:+1: :fireworks:

**Comment by bertung** [comment]
Will the new release support Java 8?

**Comment by jvilk** [comment]
The current NPM release supports it. The demo is super old, and does not. (As a grad student, I haven't had the bandwidth to update the demo with the many improvements that have occurred since!)

**Pull request merged**
