### PR TITLE
Implemented StrictMath.expm1 native method, added test check in Stric…

### PR DESCRIPTION
**Pull request by hparuyr**
I implemented StrictMath.expm1 native method during playing with doppio, also added as required by guide.
Can this be small contribution from me?

Thanks,
Paruyr

### CODE REVIEW

**Comment by jvilk** [comment]
Hey @hparuyr,

Thanks for your contribution! Just to check, you're not here due to Google Summer of Code, right? We've had an influx of users think they can start doing tasks with us for GSoC 2016, but GSoC 2016 hasn't been started yet, nor have we published any starter tasks for this year. (Regardless, I appreciate your PR!)

Could you actually move your logic for `expm1

**Comment by jimfb** [comment]
@jvilk For very small values of `x`, the expression `Math.exp(x)-1` can be inaccurate, and `d_val + 0.5*d_val*d_val;` becomes a better approximation.  For details, see: http://www.johndcook.com/blog/cpp_expm1/

@hparuyr `Math.expm1()` is defined natively as of ES6.  I believe the native implementation (when available) gives even better accuracy than your enhanced polyfill (and also better performance).  Does it make sense to have a check at the top that says `if(Math.expm1 !== undefined) return Math.expm1(x)`?

**Comment by jvilk** [comment]
@jimfb thanks for the clarification! I actually asked in my previous comment if he could make it a true polyfill, like I do for `imul` in `src/util.ts`.

**Comment by jimfb** [comment]
Ah, somehow I missed that sentence.  Your solution would be better than adding an `if` check at the top of the function :P.

**Comment by hparuyr** [comment]
Hi @jvilk,

Thank you for prompt replay. My contribution has nothing to do with "Google Summer of Code".
I added polyfill to be consistent with rest of Math methods implementations already existing in StrictMath. I did no see any Math native method checks before polyfill, but agree it would be good practice to make it.
I've made changes in src/util.ts and src/natives/java_lang.ts to use polyfill, if Math.expm1 native implementation is not available.
Thanks to @jimfb also, to provide link and explanation about my polyfill. I can add that Math.exp(x)-1 is not passing the test.

**Comment by jvilk** [comment]
Excellent. Thanks for your contribution!

**Comment by hparuyr** [comment]
Thank you for accepting :)

**Pull request merged**
