### PR TITLE
Use the async constructor of ZipFS...

### PR DESCRIPTION
**Pull request by hrj**
.. from the latest version of BrowserFS. This improves responsiveness when loading large jars.

### CODE REVIEW

**Comment by hrj** [comment]
I am not sure why travis-ci is failing. Seems unrelated to the changes in this PR?

**Comment by jvilk** [comment]
I'll look into it tonight. It looks like TS 1.8 changed its compiler options, so the initial "compile without `JVMTypes.d.ts`" pass isn't ignoring type errors, when it should.

**Comment by hrj** [comment]
Ok, I figured it out. When browserfs was updated, so did typescript. And the new typescript compiler is not happy with two things:

```
src/ClassLoader.ts(378,11): error TS17009: 'super' must be called before accessing 'this' in the constructor of a derived class.
src/natives/sun_nio.ts(310,7): error TS7027: Unreachable code detected.
```

The second one is easy to fix. But the first one is tricky.

---
Just saw you replied while I was typing this. Ok, I will wait for your changes.

**Comment by jvilk** [comment]
The first one can be fixed with:

```{ts}
super(null);
// The correct way to do this would be super(this), but we cannot reference this before calling super()
this.bootstrap = this;
```

It's hacky, but will fix the issue.

**Comment by hrj** [comment]
Fixed!

**Comment by jvilk** [comment]
Great, thanks!

**Pull request merged**
