### PR TITLE
Included the hypot native method in the java_lang.ts

### PR DESCRIPTION
**Pull request by AnishChandran**

### CODE REVIEW

**Comment by perimosocordiae** [comment]
This is a good start, thanks!

Could you move the test case to StrictMathTest.java? This will test more of the edge cases, and keeps all the StrictMath function tests in one place.

**Comment by AnishChandran** [comment]
Thanks ! I will move the test case to StrictMathTest.java and submit another pull request !

**Comment by AnishChandran** [comment]
https://github.com/AnishChandran/doppio/commit/7575291ad4dea1e6e61865ca6741be6690b185c5

**Comment by perimosocordiae** [comment]
Looks much better. One last thing: could you remove the comments about hypot higher up in the test? (We had a comment there as a TODO)

I just ran the tests from my end, and things pass here. Once the extra comments are gone, I'll merge this PR.

**Comment by AnishChandran** [comment]
Oh ! sure ! I can do it ! Can i do it for few other functions as well ?

**Comment by AnishChandran** [comment]
Which comments do you want me to remove ? the ones that i added above hypot ?

**Comment by perimosocordiae** [comment]
Lines 163-164. If you want to add more native functions, just open more pull requests :smile:

**Comment by perimosocordiae** [comment]
Thanks! Merged.

**Comment by AnishChandran** [comment]
Thanks ! :) I will try to create a new pull for someother native function !

**Pull request merged**
